# This is the configuration used to check the rubocop source code.
inherit_from: #{RUBOCOP_HOME}/config/default.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 150

Layout/LeadingCommentSpace:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Docs/Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
