# This is the configuration used to check the rubocop source code.
inherit_from: #{RUBOCOP_HOME}/config/default.yml

AllCops:
  TargetRubyVersion: 3.2

  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'

MethodLength:
  Max: 20

LineLength:
  Max: 150

LeadingCommentSpace:
  Enabled: false

CommentAnnotation:
  Enabled: false

Documentation:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
